global:
  smtp_smarthost: 'smtp.gmail.com:587'
  smtp_from: '${SMTP_USER}'
  smtp_auth_username: '${SMTP_USER}'
  smtp_auth_password: '${SMTP_PASS}'
  smtp_require_tls: true

route:
  receiver: email-team
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 1h

receivers:
  - name: email-team
    email_configs:
      - to: '${ALERT_RECEIVER}'
        send_resolved: true
