
global:
  scrape_interval: 15s
scrape_configs:
  - job_name: 'backend'
    static_configs:
      - targets: ['backend:4000']
    metrics_path: /metrics
  - job_name: 'node_exporter'
    static_configs:
      - targets: ['host.docker.internal:9100','localhost:9100']
