global:
  scrape_interval: 15s
  evaluation_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets: ['alertmanager:9093']

rule_files:
  - /etc/prometheus/alerts.yml

scrape_configs:

  - job_name: 'backend'
    static_configs:
      - targets: ['backend:4000']

  - job_name: 'node_exporter'
    static_configs:
      - targets: ['node_exporter:9100']

  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']

  - job_name: 'mongodb'
    static_configs:
      - targets: ['mongodb_exporter:9216']


# global:
#   scrape_interval: 15s
#   evaluation_interval: 15s

# scrape_configs:

#   - job_name: 'backend'
#     static_configs:
#       - targets: ['192.168.44.132:4000']

#   - job_name: 'node_exporter'
#     static_configs:
#       - targets: ['192.168.44.132:9100']

#   - job_name: 'prometheus'
#     static_configs:
#       - targets: ['192.168.44.132:9090']

#   - job_name: 'mongodb'
#     static_configs:
#       - targets: ['192.168.44.132:9216']