server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  # Scrape backend log file
  - job_name: backend-logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: backend
          app: todo-app
          __path__: /var/log/backend.log

  # Scrape container logs (optional)
  - job_name: docker-logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: docker
          __path__: /var/lib/docker/containers/*/*.log
